# --- Datasource ---
spring.datasource.url=jdbc:postgresql://localhost:5433/ledgerdb
spring.datasource.username=ledger
spring.datasource.password=ledgerpass

# --- Server ---
server.port=8081
server.error.include-message=always
server.error.include-stacktrace=always

# --- Logging ---
logging.level.org.springframework.boot.context.config=DEBUG
logging.level.org.flywaydb=DEBUG
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG

# --- JWT ---
auth.jwt.secret=cambia-esto-por-una-clave-larga-de-minimo-32-caracteres-123456